#!/bin/bash

set -e

CDUP="`git rev-parse --show-cdup`"

if [ -n "$CDUP" ]; then
    cd "$CDUP"
fi

if [ "$1" = "-r" -o "$1" = "--root" ]; then
    if [ -z "$2" ]; then
        echo "Usage: $0 [ --root ROOT ] [ files ]" 2>&1
        exit 1
    fi

    ROOT="$2"
    shift; shift
else
    ROOT="."
fi

GIT_DIR="`pwd`/`git rev-parse --git-dir`"

NEW_INDEX_FILE="$GIT_DIR/deploy-index"

GIT_INDEX_FILE="$NEW_INDEX_FILE"
GIT_WORK_TREE="`pwd`/$ROOT"

export GIT_INDEX_FILE
export GIT_DIR
export GIT_WORK_TREE

CURRENT_BRANCH=`git symbolic-ref --short HEAD`
CURRENT_COMMIT=`git rev-parse HEAD`

DEPLOY_BRANCH=deploy/$CURRENT_BRANCH
DEPLOY_BRANCH_EXISTS=`git branch --list $DEPLOY_BRANCH`

if [ -z "$DEPLOY_BRANCH_EXISTS" ]; then
    git branch $DEPLOY_BRANCH $CURRENT_BRANCH
fi


git read-tree -i --reset $DEPLOY_BRANCH --index-output="$NEW_INDEX_FILE"

cd "$GIT_WORK_TREE"

if [ -n "$1" ]; then
    git add -f "$@"
elif [ -e .gitdeploy ]; then
    while IFS= read -r ENT; do
        git add -f "$ENT"
    done < .gitdeploy
else
    git add -f .
fi

CHANGES="`git diff-index $DEPLOY_BRANCH: --cached`"

if [ -z "$CHANGES" ] && [ -z "$DEPLOY_BRANCH_EXISTS" -o -n "`git branch --contains HEAD $DEPLOY_BRANCH`" ] ; then
    echo "Nothing to do" 1>&2
    exit 1
fi

CURRENT_DEPLOY_COMMIT=`git rev-parse $DEPLOY_BRANCH`

PARENT="-p $CURRENT_COMMIT"
if [ $CURRENT_DEPLOY_COMMIT != $CURRENT_COMMIT ]; then
    PARENT="$PARENT -p $CURRENT_DEPLOY_COMMIT"
fi

TREE=`git write-tree`
COMMIT=`git commit-tree $TREE -m "deploy $CURRENT_BRANCH" $PARENT`

git update-ref refs/heads/$DEPLOY_BRANCH $COMMIT

if [ $CURRENT_DEPLOY_COMMIT != $CURRENT_COMMIT ]; then
    echo `git rev-parse --short $CURRENT_DEPLOY_COMMIT`..`git rev-parse --short $COMMIT`    $DEPLOY_BRANCH
else
    echo '[new branch]' `git rev-parse --short $COMMIT`    $DEPLOY_BRANCH
fi

exit
